src/frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\User;
use Yii;
use yii\web\Controller;

use yii\web\Cookie;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/default/login']);
        }

        /* @var $currentUser User */
        $currentUser = Yii::$app->user->identity;

        $limit = Yii::$app->params['feedPostLimit'];
        $feedItems = $currentUser->getFeed($limit);

        return $this->render('index', [
            'feedItems' => $feedItems,
            'currentUser' => $currentUser,
        ]);
    }

    public function actionMyProfile()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/default/login']);
        }

        $currentUser = Yii::$app->user->identity;

        return $this->redirect(['/profile/' . $currentUser->getId()]);
    }

    /**
     * Change language
     * @return mixed
     */
    public function actionLanguage()
    {
        // Hometask: check if language is supported
        $language = Yii::$app->request->post('language');
        Yii::$app->language = $language;

        $languageCookie = new Cookie([
            'name' => 'language',
            'value' => $language,
            'expire' => time() + 60 * 60 * 24 * 30, // 30 days
        ]);
        Yii::$app->response->cookies->add($languageCookie);

        return $this->redirect(Yii::$app->request->referrer);
    }

}

src/frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);

$allowLocalizationChange = false;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 image-header-block center-block ">
                <a href="/">
                    <img src="/img/head.png" class="image-header">
                </a>

                <?php if($allowLocalizationChange):?>
                    <div class="col-md-2">
                        <?= Html::beginForm(['/site/language']) ?>
                        <?= Html::dropDownList('language', Yii::$app->language, ['en-US' => 'English', 'ru-RU' => 'Русский']) ?>
                        <?= Html::submitButton('Change') ?>
                        <?= Html::endForm() ?>
                    </div>
                <?php endif; ?>


                <ul class="nav nav-pills center-block" style="margin: 0 auto;">
                    <li class="nav-item">
                        <a class="nav-link active" href="/site/index">Главная</a>
                    </li>
                    <?php if (Yii::$app->user->isGuest): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="/user/default/login">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/user/default/signup">Зарегистрироваться</a>
                        </li>
                    <?php else: ?>
                        <li class="nav-item">
                            <a class="nav-link" href="/site/my-profile"><?php echo Yii::t('menu', 'My profile')?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/post/default/create">Добавить пост</a>
                        </li>
                        <li class="nav-item">
                            <form id="logout_form" action="/user/default/logout" method="post">
                                <input type="hidden" name="<?=Yii::$app->request->csrfParam; ?>" value="<?=Yii::$app->request->getCsrfToken(); ?>" >
                                <a class="nav-link" href="#" onclick="document.getElementById('logout_form').submit();">Выйти</a>
                            </form>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="col-md-2"></div>
        <div class="col-md-8 image-header-block center-block">

            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
        <div class="col-md-2 "></div>
    </div>
</div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>